# @credits https://github.com/c0re100/qBittorrent-Enhanced-Edition
name: matrix multi build and release - customs tags

on:
  workflow_dispatch:
    inputs:
      distinct_id:
      skip_rerun:
        description: "Skip rerun?"
        required: true
        type: boolean
      retries:
        description: "Number of rerun retries"
        required: true
        default: "1"
        type: choice
        options: ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_id: [alpine]
        os_version_id: [edge]
        qbt_libtorrent_version: [1.2]
        qbt_qt_version: [5]
        qbt_build_tool: [qmake]
        qbt_qbittorrent_tag: [release-4.3.9]
        arch_type:
          [
            armel,
            armhf,
            armv7,
            aarch64,
            x86_64,
            x86,
            s390x,
            powerpc,
            ppc64el,
            mips,
            mipsel,
            mips64,
            mips64el,
            riscv64,
          ]

    name: "${{ matrix.arch_type }}-qbittorent-nox-legacy"

    env:
      qbt_build_dir: "qbt-build"
      name: "${{ matrix.arch_type }}-libtorrent-v1.2"
      draft_status: true
    outputs:
      draft_id: "${{ steps.release_id.outputs.id }}"
      draft_status: "${{ steps.draft_status.outputs.draft_status }}"
      release_tag: "${{ steps.release_tag.outputs.release_tag }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Host - phased updates
        run: printf '%s\n' 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates

      - name: Host - set up lunar repo -t lunar
        run: |
          printf '%b\n' 'Package: *\nPin: release n=lunar\nPin-Priority: 50' | sudo tee /etc/apt/preferences
          printf '%b\n' 'deb http://archive.ubuntu.com/ubuntu/ lunar main universe restricted' | sudo tee /etc/apt/sources.list.d/lunar.list

      - name: Host - update
        run: sudo apt-get update

      - name: Host - upgrade
        run: sudo apt-get -y upgrade

      - name: Host - set up qemu-user-static binfmt-support from lunar
        run: sudo apt install -t lunar libpipeline1 qemu-user-static binfmt-support

      - name: Host - Create Docker template env file
        run: |
          printf '%s\n' "qbt_libtorrent_version=${{ matrix.qbt_libtorrent_version }}" > env.custom
          printf '%s\n' "qbt_qt_version=${{ matrix.qbt_qt_version }}" >> env.custom
          printf '%s\n' "qbt_build_tool=${{ matrix.qbt_build_tool }}" >> env.custom
          printf '%s\n' "qbt_cross_name=${{ matrix.arch_type }}" >> env.custom
          printf '%s\n' "qbt_patches_url=${{ github.repository }}" >> env.custom
          printf '%s\n' "qbt_skip_icu=yes" >> env.custom
          # printf '%s\n' "qbt_boost_tag=" >> env.custom
          # printf '%s\n' "qbt_libtorrent_tag=" >> env.custom
          # printf '%s\n' "qbt_qt_tag=" >> env.custom
          printf '%s\n' "qbt_qbittorrent_tag=${{ matrix.qbt_qbittorrent_tag }}" >> env.custom
          printf '%s\n' "qbt_libtorrent_master_jamfile=no" >> env.custom
          printf '%s\n' "qbt_workflow_files=yes" >> env.custom
          printf '%s\n' "qbt_workflow_artifacts=no" >> env.custom
          # printf '%s\n' "qbt_cache_dir= >> env.custom
          printf '%s\n' "qbt_optimise_strip=yes" >> env.custom
          printf '%s\n' "qbt_build_debug=no" >> env.custom
          printf '%s\n' "qbt_revision_url=${{ github.repository }}" >> env.custom

      - name: Host - Create docker multiarch container
        run: docker run --name multiarch -it -d --env-file env.custom -w /root -v ${{ github.workspace }}:/root ${{ matrix.os_id }}:${{ matrix.os_version_id }}

      - name: Docker - apk update
        run: docker exec -w /root multiarch apk update

      - name: Docker - apk install bash
        run: docker exec -w /root multiarch apk add bash

      - name: Docker - Bootstrap
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh -bs-a

      - name: Docker - zlib-ng
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh zlib

      - name: Docker - iconv
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh iconv

      - name: Docker - icu
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh icu

      - name: Docker - openssl
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh openssl

      - name: Docker - boost
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh boost

      - name: Docker - libtorrent
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh libtorrent

      - name: Docker - qtbase
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh qtbase

      - name: Docker - qttools
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh qttools

      - name: Docker - qbittorrent
        run: docker exec -w /root multiarch bash qbittorrent-nox-static.sh qbittorrent

      - name: Docker - Set release asset name
        run: docker exec -w /root/${{ env.qbt_build_dir }}/completed multiarch mv -f qbittorrent-nox ${{ matrix.arch_type }}-qbittorrent-nox

      - name: Docker - Release Info
        run: docker exec -w /root/${{ env.qbt_build_dir }}/release_info multiarch bash -c 'mv *.md *.json '/root/${{ env.qbt_build_dir }}/completed''

      - name: Host - Upload libtorrent-${{ matrix.arch_type }}-qbittorrent-nox and release info artifact
        uses: actions/upload-artifact@v3
        with:
          name: libtorrent-${{ matrix.arch_type }}-qbittorrent-nox
          path: |
            ${{ env.qbt_build_dir }}/completed/*
            !${{ env.qbt_build_dir }}/completed/*.png

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    if: always() && contains(needs.*.result, 'success') && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')

    name: "Publish release libtorrent-v${{ matrix.libtorrent_version }}"

    env:
      qbt_build_dir: "qbt-build"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pandoc - Bootstrap
        run: |
          pandoc_git_tag="$(git ls-remote -q -t --refs https://github.com/jgm/pandoc.git | awk '/tags\/[0-9]/{sub("refs/tags/", ""); print $2 }' | awk '!/^$/' | sort -rV | head -n 1)"
          curl -sLo- "https://github.com/jgm/pandoc/releases/latest/download/pandoc-${pandoc_git_tag}-linux-amd64.tar.gz" | tar xzf - --strip-components 2 -C "$(pwd)" --exclude="share"

      - name: Host - Download qbittorrent-nox artifacts
        uses: actions/download-artifact@v4

      - name: Host - artifacts organise for release
        run: |
          mkdir -p "releases"
          for files in libtorrent-*-qbittorrent-nox; do
              cp -rf ${files}/* "releases/"
          done

      - name: Host - merge release-info
        run: |
          paste -d '\n' releases/qt5-*-release.md | uniq > tmp-release.md
          ./pandoc --wrap=preserve -f gfm tmp-release.md -t gfm -o release.md

          mv -f releases/qt5-dependency-version.json dependency-version.json

      - name: Host - Bootstrap release tag
        run: printf '%s\n' "release_tag=$(cat releases/tag.md)" >> $GITHUB_ENV

      - name: Host - Bootstrap release title
        run: printf '%s\n' "release_title=$(cat releases/title.md)" >> $GITHUB_ENV

      - name: Host- Create release - tag - assets
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          artifacts: "releases/*-qbittorrent-nox,dependency-version.json"
          replacesArtifacts: true
          tag: "${{ env.release_tag }}"
          name: "${{ env.release_title }}"
          bodyFile: "release.md"
          allowUpdates: true

  rerun-on-failure:
    if: failure() && inputs.skip_rerun == '0'
    name: rerun-on-failure
    needs: release
    permissions:
      actions: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v4
      - name: Trigger rerun workflow on job failures
        run: |
          inputs_retries="${{ inputs.retries }}"
          gh workflow run rerun.yml -f run_id=${{ github.run_id }} -f attempts=${{ github.run_attempt }} -f retries=${inputs_retries:-5}
